name: flutter_swarm_frontend
description: "Multi-Agent Flutter Development System - Real-time Monitoring Dashboard"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Material Design
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  
  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  
  # Networking and WebSocket
  http: ^1.2.1
  web_socket_channel: ^3.0.1
  dio: ^5.7.0
  
  # Real-time Updates
  socket_io_client: ^3.0.1
  
  # Charts and Data Visualization
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.58
  
  # JSON and Data Handling
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.3
  
  # Logging
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
