image: cirrusci/flutter:stable

stages:
  - test
  - build
  - deploy

variables:
  FLUTTER_VERSION: "3.16.0"

cache:
  paths:
    - .pub-cache/

before_script:
  - flutter pub get

test:
  stage: test
  script:
    - flutter analyze
    - flutter test --coverage
  coverage: '/lines......: \d+\.\d+%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml

build:android:
  stage: build
  script:
    - flutter build apk --release
    - flutter build appbundle --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    expire_in: 1 week
  only:
    - main
    - develop

build:ios:
  stage: build
  tags:
    - macos
  script:
    - flutter build ios --release --no-codesign
  artifacts:
    paths:
      - build/ios/iphoneos/Runner.app
    expire_in: 1 week
  only:
    - main
    - develop

build:web:
  stage: build
  script:
    - flutter build web --release
  artifacts:
    paths:
      - build/web/
    expire_in: 1 week
  only:
    - main
    - develop

deploy:staging:
  stage: deploy
  environment:
    name: staging
    url: https://staging.example.com
  script:
    - echo "Deploying to staging..."
    # Add your staging deployment commands here
  dependencies:
    - build:web
  only:
    - develop

deploy:production:
  stage: deploy
  environment:
    name: production
    url: https://example.com
  script:
    - echo "Deploying to production..."
    # Add your production deployment commands here
  dependencies:
    - build:android
    - build:ios
    - build:web
  only:
    - main
  when: manual
