behavior_config:
  auto_retry_failed_tasks: true
  enable_collaboration: true
  enable_learning: true
  importance_threshold: 0.5
  max_concurrent_tasks: 5
  memory_retention_hours: 24
  task_timeout: 600
custom_parameters:
  custom_threshold: 0.8
  debug_mode: false
  specialized_feature_enabled: true
enabled: true
model_config:
  max_retries: 3
  max_tokens: 4000
  model: gpt-4
  provider: openai
  temperature: 0.7
  timeout: 300
prompt_config:
  constraint_instructions:
  - Follow Flutter best practices
  - Ensure accessibility compliance
  - Maintain security standards
  custom_instructions:
  - Always provide detailed explanations
  - Include code examples when relevant
  - Consider performance implications
  response_format_instructions: Provide responses in JSON format when requested
  system_prompt_file: custom_prompt.txt
