behavior_config:
  max_concurrent_tasks: 3
capabilities:
- performance_analysis
- optimization
- monitoring_setup
enabled: true
model_config:
  max_retries: 3
  max_tokens: 7000
  model: claude-sonnet-4-20250514
  provider: anthropic
  temperature: 0.3
  timeout: 700
prompt_config:
  system_prompt_file: performance_prompt.txt
